ALTER TABLE frameref DROP FOREIGN KEY fk_frameref_frameid;
ALTER TABLE frameref DROP FOREIGN KEY fk_frameref_synsetid;
ALTER TABLE frameref DROP FOREIGN KEY fk_frameref_wordid;
ALTER TABLE legacy2030 DROP FOREIGN KEY fk_legacy_synsetid;
ALTER TABLE legacy2130 DROP FOREIGN KEY fk_legacy2_synsetid;
ALTER TABLE lexlinkref DROP FOREIGN KEY fk_lexlinkref_linkid;
ALTER TABLE lexlinkref DROP FOREIGN KEY fk_lexlinkref_synset1id;
ALTER TABLE lexlinkref DROP FOREIGN KEY fk_lexlinkref_synset2id;
ALTER TABLE lexlinkref DROP FOREIGN KEY fk_lexlinkref_word1id;
ALTER TABLE lexlinkref DROP FOREIGN KEY fk_lexlinkref_word2id;
ALTER TABLE morphref DROP FOREIGN KEY fk_morphref_morphid;
ALTER TABLE morphref DROP FOREIGN KEY fk_morphref_wordid;
ALTER TABLE sample DROP FOREIGN KEY fk_sample_synsetid;
ALTER TABLE semlinkref DROP FOREIGN KEY fk_semlinkref_linkid;
ALTER TABLE semlinkref DROP FOREIGN KEY fk_semlinkref_synset1id;
ALTER TABLE semlinkref DROP FOREIGN KEY fk_semlinkref_synset2id;
ALTER TABLE sense DROP FOREIGN KEY fk_sense_synsetid;
ALTER TABLE sense DROP FOREIGN KEY fk_sense_wordid;
ALTER TABLE sentenceref DROP FOREIGN KEY fk_sentenceref_sentenceid;
ALTER TABLE sentenceref DROP FOREIGN KEY fk_sentenceref_synsetid;
ALTER TABLE sentenceref DROP FOREIGN KEY fk_sentenceref_wordid;
ALTER TABLE synset DROP FOREIGN KEY fk_synset_categoryid;
ALTER TABLE vnexampleref DROP FOREIGN KEY fk_vnexampleref_exampleid;
ALTER TABLE vnexampleref DROP FOREIGN KEY fk_vnexampleref_frameid;
ALTER TABLE vnframeref DROP FOREIGN KEY fk_vnframeref_classid;
ALTER TABLE vnframeref DROP FOREIGN KEY fk_vnframeref_frameid;
ALTER TABLE vnframeref DROP FOREIGN KEY fk_vnframeref_wordid;
ALTER TABLE vnrole DROP FOREIGN KEY fk_vnrole_classid;
ALTER TABLE vnrole DROP FOREIGN KEY fk_vnrole_roletypeid;
ALTER TABLE vnrole DROP FOREIGN KEY fk_vnrole_wordid;
ALTER TABLE wordposition DROP FOREIGN KEY fk_wordposition_synsetid;
ALTER TABLE wordposition DROP FOREIGN KEY fk_wordposition_wordid;
ALTER TABLE xwnparselft DROP FOREIGN KEY fk_xwnparselft_synsetid;
ALTER TABLE xwnwsd DROP FOREIGN KEY fk_xwnwsd_synsetid;
ALTER TABLE legacy2021 DROP INDEX k_legacy1_synsetid2;
ALTER TABLE legacy2021 DROP INDEX k_legacy1_synsetid;
ALTER TABLE legacy2030 DROP INDEX k_legacy_synsetid2;
ALTER TABLE legacy2030 DROP INDEX k_legacy_synsetid;
ALTER TABLE legacy2130 DROP INDEX k_legacy2_synsetid2;
ALTER TABLE legacy2130 DROP INDEX k_legacy2_synsetid;
ALTER TABLE legacysensekey2021 DROP INDEX k_legacysensekey1_sensekey;
ALTER TABLE legacysensekey2030 DROP INDEX k_legacysensekey_sensekey;
ALTER TABLE legacysensekey2130 DROP INDEX k_legacysensekey2_sensekey;
ALTER TABLE lexlinkref DROP INDEX k_lexlinkref_synset1id_word1id;
ALTER TABLE lexlinkref DROP INDEX k_lexlinkref_synset2id_word2id;
ALTER TABLE morphref DROP INDEX k_morphref_morphid;
ALTER TABLE morphref DROP INDEX k_morphref_wordid;
ALTER TABLE sample DROP INDEX k_sample_synsetid;
ALTER TABLE semlinkref DROP INDEX k_semlinkref_synset1id;
ALTER TABLE semlinkref DROP INDEX k_semlinkref_synset2id;
ALTER TABLE sense DROP INDEX k_sense_synsetid;
ALTER TABLE sense DROP INDEX k_sense_wordid;
ALTER TABLE vnrole DROP INDEX k_vnrole_wordid_synsetid;
ALTER TABLE xwnparselft DROP INDEX k_wnparselft_synsetid;
ALTER TABLE casedword DROP INDEX unq_casedword_lemma;
ALTER TABLE morphdef DROP INDEX unq_morphdef_lemma;
ALTER TABLE vnclass DROP INDEX unq_vnclass_class;
ALTER TABLE vnexampledef DROP INDEX unq_vnexampledef_example;
ALTER TABLE vnframedef DROP INDEX unq_vnframedef_all;
ALTER TABLE vnframeref DROP INDEX unq_vnframeref_wordid_synsetid_frameid_classid;
ALTER TABLE vnrole DROP INDEX unq_vnrole_wordid_synsetid_classid_roletypeid_selrestrsid;
ALTER TABLE vnroletype DROP INDEX unq_vnroletype_type;
ALTER TABLE vnselrestr DROP INDEX unq_vnselrestr_value_type;
ALTER TABLE vnselrestrs DROP INDEX unq_vnselrestrs_selrestrs;
ALTER TABLE word DROP INDEX unq_word_lemma;
ALTER TABLE xwnparselft DROP INDEX unq_xwnparselft_synsetid_parse_lft;
ALTER TABLE xwnwsd DROP INDEX unq_xwnwsd_synsetid_wsd_text;
ALTER TABLE casedword DROP PRIMARY KEY;
ALTER TABLE framedef DROP PRIMARY KEY;
ALTER TABLE frameref DROP PRIMARY KEY;
ALTER TABLE legacy2021 DROP PRIMARY KEY;
ALTER TABLE legacy2030 DROP PRIMARY KEY;
ALTER TABLE legacy2130 DROP PRIMARY KEY;
ALTER TABLE legacysensekey2021 DROP PRIMARY KEY;
ALTER TABLE legacysensekey2030 DROP PRIMARY KEY;
ALTER TABLE legacysensekey2130 DROP PRIMARY KEY;
ALTER TABLE lexlinkref DROP PRIMARY KEY;
ALTER TABLE morphdef DROP PRIMARY KEY;
ALTER TABLE morphref DROP PRIMARY KEY;
ALTER TABLE sample DROP PRIMARY KEY;
ALTER TABLE semlinkref DROP PRIMARY KEY;
ALTER TABLE sense DROP PRIMARY KEY;
ALTER TABLE sentencedef DROP PRIMARY KEY;
ALTER TABLE sentenceref DROP PRIMARY KEY;
ALTER TABLE synset DROP PRIMARY KEY;
ALTER TABLE vnclass DROP PRIMARY KEY;
ALTER TABLE vnexampledef DROP PRIMARY KEY;
ALTER TABLE vnexampleref DROP PRIMARY KEY;
ALTER TABLE vnframedef DROP PRIMARY KEY;
ALTER TABLE vnframeref DROP PRIMARY KEY;
ALTER TABLE vnrole DROP PRIMARY KEY;
ALTER TABLE vnroletype DROP PRIMARY KEY;
ALTER TABLE vnselrestr DROP PRIMARY KEY;
ALTER TABLE vnselrestrs DROP PRIMARY KEY;
ALTER TABLE word DROP PRIMARY KEY;
ALTER TABLE wordposition DROP PRIMARY KEY;
ALTER TABLE casedword ADD CONSTRAINT pk_casedword_wordid PRIMARY KEY (wordid);
ALTER TABLE framedef ADD CONSTRAINT pk_framedef PRIMARY KEY (frameid);
ALTER TABLE frameref ADD CONSTRAINT pk_frameref PRIMARY KEY (synsetid,wordid,frameid);
ALTER TABLE legacy2021 ADD CONSTRAINT pk_legacy1 PRIMARY KEY (mapid);
ALTER TABLE legacy2030 ADD CONSTRAINT pk_legacy PRIMARY KEY (mapid);
ALTER TABLE legacy2130 ADD CONSTRAINT pk_legacy2 PRIMARY KEY (mapid);
ALTER TABLE legacysensekey2021 ADD CONSTRAINT pk_legacysensekey1 PRIMARY KEY (mapid,sensekey);
ALTER TABLE legacysensekey2030 ADD CONSTRAINT pk_legacysensekey PRIMARY KEY (mapid,sensekey);
ALTER TABLE legacysensekey2130 ADD CONSTRAINT pk_legacysensekey2 PRIMARY KEY (mapid,sensekey);
ALTER TABLE lexlinkref ADD CONSTRAINT pk_lexlinkref_wordid_synsetid_linkid PRIMARY KEY (word1id,synset1id,word2id,synset2id,linkid);
ALTER TABLE morphdef ADD CONSTRAINT pk_morphdef PRIMARY KEY (morphid);
ALTER TABLE morphref ADD CONSTRAINT pk_morphref PRIMARY KEY(morphid,pos,wordid);
ALTER TABLE sample ADD CONSTRAINT pk_sample_synsetid_sampleid PRIMARY KEY (synsetid,sampleid);
ALTER TABLE semlinkref ADD CONSTRAINT pk_semlinkref PRIMARY KEY (synset1id,synset2id,linkid);
ALTER TABLE sense ADD CONSTRAINT pk_sense_synsetid_wordid PRIMARY KEY (synsetid,wordid);
ALTER TABLE sentencedef ADD CONSTRAINT pk_sentencedef PRIMARY KEY(sentenceid);
ALTER TABLE sentenceref ADD CONSTRAINT pk_sentenceref PRIMARY KEY (synsetid,wordid,sentenceid);
ALTER TABLE synset ADD CONSTRAINT pk_synset_synsetid PRIMARY KEY (synsetid);
ALTER TABLE vnclass ADD CONSTRAINT pk_vnclass PRIMARY KEY (classid);
ALTER TABLE vnexampledef ADD CONSTRAINT pk_vnexampledef PRIMARY KEY (exampleid);
ALTER TABLE vnexampleref ADD CONSTRAINT pk_vnexampleref PRIMARY KEY (frameid,exampleid);
ALTER TABLE vnframedef ADD CONSTRAINT pk_vnframedef PRIMARY KEY (frameid);
ALTER TABLE vnframeref ADD CONSTRAINT pk_vnframeref PRIMARY KEY (framerefid);
ALTER TABLE vnrole ADD CONSTRAINT pk_vnrole PRIMARY KEY (roleid);
ALTER TABLE vnroletype ADD CONSTRAINT pk_vnroletype PRIMARY KEY (roletypeid);
ALTER TABLE vnselrestr ADD CONSTRAINT pk_vnselrestr PRIMARY KEY (selrestrid);
ALTER TABLE vnselrestrs ADD CONSTRAINT pk_vnselrestrs PRIMARY KEY (selrestrsid);
ALTER TABLE word ADD CONSTRAINT pk_word_wordid PRIMARY KEY (wordid);
ALTER TABLE wordposition ADD CONSTRAINT pk_wordposition PRIMARY KEY wordposition (synsetid,wordid);
ALTER TABLE casedword ADD CONSTRAINT unq_casedword_lemma UNIQUE KEY (lemma);
ALTER TABLE morphdef ADD CONSTRAINT unq_morphdef_lemma UNIQUE KEY (lemma);
ALTER TABLE vnclass ADD CONSTRAINT unq_vnclass_class UNIQUE KEY (class);
ALTER TABLE vnexampledef ADD CONSTRAINT unq_vnexampledef_example UNIQUE KEY (example);
ALTER TABLE vnframedef ADD CONSTRAINT unq_vnframedef_all UNIQUE KEY (number,xtag,description1,description2,syntax(256),semantics(256));
ALTER TABLE vnframeref ADD CONSTRAINT unq_vnframeref_wordid_synsetid_frameid_classid UNIQUE KEY (wordid,synsetid,frameid,classid);
ALTER TABLE vnrole ADD CONSTRAINT unq_vnrole_wordid_synsetid_classid_roletypeid_selrestrsid UNIQUE KEY (wordid,synsetid,classid,roletypeid,selrestrsid);
ALTER TABLE vnroletype ADD CONSTRAINT unq_vnroletype_type UNIQUE KEY (type);
ALTER TABLE vnselrestr ADD CONSTRAINT unq_vnselrestr_value_type UNIQUE KEY (value,type);
ALTER TABLE vnselrestrs ADD CONSTRAINT unq_vnselrestrs_selrestrs UNIQUE KEY (selrestrs(512));
ALTER TABLE word ADD CONSTRAINT unq_word_lemma UNIQUE KEY (lemma);
ALTER TABLE xwnparselft ADD CONSTRAINT unq_xwnparselft_synsetid_parse_lft UNIQUE KEY (synsetid,parse(256),lft(256));
ALTER TABLE xwnwsd ADD CONSTRAINT unq_xwnwsd_synsetid_wsd_text UNIQUE KEY (synsetid,wsd(256),`text`(256));
ALTER TABLE legacy2021 ADD INDEX k_legacy1_synsetid (synsetid);
ALTER TABLE legacy2021 ADD INDEX k_legacy1_synsetid2 (synsetid2);
ALTER TABLE legacy2030 ADD INDEX k_legacy_synsetid (synsetid);
ALTER TABLE legacy2030 ADD INDEX k_legacy_synsetid2 (synsetid2);
ALTER TABLE legacy2130 ADD INDEX k_legacy2_synsetid (synsetid);
ALTER TABLE legacy2130 ADD INDEX k_legacy2_synsetid2 (synsetid2);
ALTER TABLE legacysensekey2021 ADD INDEX k_legacysensekey1_sensekey (sensekey);
ALTER TABLE legacysensekey2030 ADD INDEX k_legacysensekey_sensekey (sensekey);
ALTER TABLE legacysensekey2130 ADD INDEX k_legacysensekey2_sensekey (sensekey);
ALTER TABLE lexlinkref ADD INDEX k_lexlinkref_synset1id_word1id (synset1id,word1id);
ALTER TABLE lexlinkref ADD INDEX k_lexlinkref_synset2id_word2id (synset2id,word2id);
ALTER TABLE morphref ADD INDEX k_morphref_morphid (morphid);
ALTER TABLE morphref ADD INDEX k_morphref_wordid (wordid);
ALTER TABLE sample ADD INDEX k_sample_synsetid (synsetid);
ALTER TABLE semlinkref ADD INDEX k_semlinkref_synset1id (synset1id);
ALTER TABLE semlinkref ADD INDEX k_semlinkref_synset2id (synset2id);
ALTER TABLE sense ADD INDEX k_sense_synsetid (synsetid);
ALTER TABLE sense ADD INDEX k_sense_wordid (wordid);
ALTER TABLE vnrole ADD INDEX k_vnrole_wordid_synsetid (wordid,synsetid);
ALTER TABLE xwnparselft ADD INDEX k_wnparselft_synsetid (synsetid);
ALTER TABLE frameref ADD CONSTRAINT fk_frameref_frameid FOREIGN KEY (frameid) REFERENCES framedef(frameid);
ALTER TABLE frameref ADD CONSTRAINT fk_frameref_synsetid FOREIGN KEY (synsetid) REFERENCES synset(synsetid);
ALTER TABLE frameref ADD CONSTRAINT fk_frameref_wordid FOREIGN KEY (wordid) REFERENCES word(wordid);
ALTER TABLE legacy2030 ADD CONSTRAINT fk_legacy_synsetid FOREIGN KEY (synsetid) REFERENCES synset(synsetid);
ALTER TABLE legacy2130 ADD CONSTRAINT fk_legacy2_synsetid FOREIGN KEY (synsetid) REFERENCES synset(synsetid);
ALTER TABLE lexlinkref ADD CONSTRAINT fk_lexlinkref_linkid FOREIGN KEY (linkid) REFERENCES linkdef (linkid);
ALTER TABLE lexlinkref ADD CONSTRAINT fk_lexlinkref_synset1id FOREIGN KEY (synset1id) REFERENCES synset (synsetid);
ALTER TABLE lexlinkref ADD CONSTRAINT fk_lexlinkref_synset2id FOREIGN KEY (synset2id) REFERENCES synset (synsetid);
ALTER TABLE lexlinkref ADD CONSTRAINT fk_lexlinkref_word1id FOREIGN KEY (word1id) REFERENCES word (wordid);
ALTER TABLE lexlinkref ADD CONSTRAINT fk_lexlinkref_word2id FOREIGN KEY (word2id) REFERENCES word (wordid);
ALTER TABLE morphref ADD CONSTRAINT fk_morphref_morphid FOREIGN KEY (morphid) REFERENCES morphdef(morphid);
ALTER TABLE morphref ADD CONSTRAINT fk_morphref_wordid FOREIGN KEY (wordid) REFERENCES word(wordid);
ALTER TABLE sample ADD CONSTRAINT fk_sample_synsetid FOREIGN KEY (synsetid) REFERENCES synset(synsetid);
ALTER TABLE semlinkref ADD CONSTRAINT fk_semlinkref_linkid FOREIGN KEY (linkid) REFERENCES linkdef (linkid);
ALTER TABLE semlinkref ADD CONSTRAINT fk_semlinkref_synset1id FOREIGN KEY (synset1id) REFERENCES synset (synsetid);
ALTER TABLE semlinkref ADD CONSTRAINT fk_semlinkref_synset2id FOREIGN KEY (synset2id) REFERENCES synset (synsetid);
ALTER TABLE sense ADD CONSTRAINT fk_sense_synsetid FOREIGN KEY (synsetid) REFERENCES synset(synsetid);
ALTER TABLE sense ADD CONSTRAINT fk_sense_wordid FOREIGN KEY (wordid) REFERENCES word(wordid);
ALTER TABLE sentenceref ADD CONSTRAINT fk_sentenceref_sentenceid FOREIGN KEY (sentenceid) REFERENCES sentencedef(sentenceid);
ALTER TABLE sentenceref ADD CONSTRAINT fk_sentenceref_synsetid FOREIGN KEY (synsetid) REFERENCES synset(synsetid);
ALTER TABLE sentenceref ADD CONSTRAINT fk_sentenceref_wordid FOREIGN KEY (wordid) REFERENCES word(wordid);
ALTER TABLE synset ADD CONSTRAINT fk_synset_categoryid FOREIGN KEY (categoryid) REFERENCES categorydef (categoryid);
ALTER TABLE vnexampleref ADD CONSTRAINT fk_vnexampleref_exampleid FOREIGN KEY (exampleid) REFERENCES vnexampledef(exampleid);
ALTER TABLE vnexampleref ADD CONSTRAINT fk_vnexampleref_frameid FOREIGN KEY (frameid) REFERENCES vnframedef(frameid);
ALTER TABLE vnframeref ADD CONSTRAINT fk_vnframeref_classid FOREIGN KEY (classid) REFERENCES vnframedef(classid);
ALTER TABLE vnframeref ADD CONSTRAINT fk_vnframeref_frameid FOREIGN KEY (frameid) REFERENCES vnframedef(frameid);
ALTER TABLE vnframeref ADD CONSTRAINT fk_vnframeref_wordid FOREIGN KEY (wordid) REFERENCES word(wordid);
ALTER TABLE vnrole ADD CONSTRAINT fk_vnrole_classid FOREIGN KEY (classid) REFERENCES vnclass(classid);
ALTER TABLE vnrole ADD CONSTRAINT fk_vnrole_roletypeid FOREIGN KEY (roletypeid) REFERENCES vnroletype(roletypeid);
ALTER TABLE vnrole ADD CONSTRAINT fk_vnrole_wordid FOREIGN KEY (wordid) REFERENCES word(wordid);
ALTER TABLE wordposition ADD CONSTRAINT fk_wordposition_synsetid FOREIGN KEY (synsetid) REFERENCES synset (synsetid);
ALTER TABLE wordposition ADD CONSTRAINT fk_wordposition_wordid FOREIGN KEY (wordid) REFERENCES word (wordid);
ALTER TABLE xwnparselft ADD CONSTRAINT fk_xwnparselft_synsetid FOREIGN KEY (synsetid) REFERENCES synset(synsetid);
ALTER TABLE xwnwsd ADD CONSTRAINT fk_xwnwsd_synsetid FOREIGN KEY (synsetid) REFERENCES synset(synsetid);
